name: CI

on:
  push:
    branches: 'main'
  pull_request:
    branches: '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]    
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: go get -u -t ./...
    - name: Install golangci-lint
      run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.34.1
    - name: Lint
      run: golangci-lint run ./...
